### ISSUE TITLE
Time quickly becomes stale

### ISSUE THREAD

**Issue by fredley** [smaslennikov/whattimeisitrightmeow#12]
When I load the page, the time is correctish. However, if I leave the page open, the time quickly becomes stale. Can a frontend module be introduced that refreshes the page every few seconds so that the time is always correctish?

**Comment by slavaaaaaaaaaa** [comment]
We could do [this](https://stackoverflow.com/questions/8711888/auto-refresh-code-in-html-using-meta-tags) junk but it depends on your browser whether that'd work

**Comment by fredley** [comment]
Seems to have support back to IE6, so don't see why browser compatibility would be an issue.

**Comment by slavaaaaaaaaaa** [comment]
Neat, I can throw this in later today then

**Comment by slavaaaaaaaaaa** [comment]
https://github.com/smaslennikov/whattimeisitrightmeow/commit/eadab279cd115aa51ebf5a0602ce8be94e09a2cb fixes this (I think).
