### ISSUE TITLE
Occasionally skips a minute

### ISSUE THREAD

**Issue by neuhaus** [smaslennikov/whattimeisitrightmeow#2]
See https://github.com/smaslennikov/whattimeisitrightmeow/commit/e7c2da831cd245a2571f31c4ca2465459fc3319b for an example where it skipped 1:54
The delay in the update script should be less than one minute to take into account the time it takes to run the other commands.

**Comment by fredley** [comment]
Alternatively add a crontab configuration, this would be more robust to system restarts. A Puppet configuration could automate the process of installing the cron.

**Comment by neuhaus** [comment]
If you want to keep it around as a bash script, you can use `date +%S` to find the seconds elapsed in the current minute and sleep exactly until the beginning of the next minute to improve the accuracy of the time.

**Comment by slavaaaaaaaaaa** [comment]
@fredley crontab was the original plan, but that's too stable for this kinda thing. We're aiming for devops solutions here.

#5 fixes it though. Thank you sirs!

**Comment by slavaaaaaaaaaa** [comment]
Humm, #5 actually brought in this bug:

```bash
./bin/build.sh: line 17: 60 - 08: value too great for base (error token is "08")
```

Gonna have to fix that with a sed/awk combo, of course.

**Comment by neuhaus** [comment]
No need for sed/awk, just get `date` to disable padding. I issued pull request #10.

**Comment by slavaaaaaaaaaa** [comment]
@neuhaus in the spirit of what this is, sed/awk was my badmode suggestion. Thank you for the PR, merged.
