### ISSUE TITLE
Implement API

### ISSUE THREAD

**Issue by elmarti** [smaslennikov/whattimeisitrightmeow#7]
I am currently using 
`$.get("index.html").children[0].children[0].children[0]` 
in all of my projects on setInterval, would be nice to see an extensive API for real time.

**Comment by hussfelt** [comment]
@elmarti could be fixed by #3, PR ready at #6 .

**Comment by slavaaaaaaaaaa** [comment]
#6 is merged, allowing for this. Cheers!
